# Generated by Django 3.2.18 on 2023-04-03 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='id',
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloth',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='OrderCloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderclothes', to='app1.cloth')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderclothes', to='app1.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='cloth',
            field=models.ManyToManyField(through='app1.OrderCloth', to='app1.Cloth'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app1.user'),
        ),
    ]
